### PR TITLE
make smell-baron return the status code of the running process when finishing

### PR DESCRIPTION
**Pull request by DylanSale**
I needed this for tests to error correctly when they finish.

### CODE REVIEW

**Comment by insidewhy** [comment]
Hi, thanks for your contribution, this is a great idea but the code isn't quite right, I'll add some comments.

**Comment by insidewhy** [comment]
Cool nice work, could you merge those two commits into one, then I'm happy to pull. Let me know if you need any help with the commit merging.

**Comment by insidewhy** [comment]
Sorry meant to say `three` instead of `two` there.

**Comment by DylanSale** [comment]
:+1:

**Pull request merged**
